version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db 
  
  basketdb:
    container_name: basketdb
    restart: always
    ports:
        - "6379:6379"
  
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnet.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
        - pgadmin_data:/root/.pgadmin

  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=SwN12345678
    restart: always
    ports:
      - "1466:1433"  
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" 
      - "15672:15672"

  portainer:
    container_name: portainer
    restart: always
    ports:
        - "8000:8000"
        - "9000:9000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
  
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=8002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456-a
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017" 
    depends_on:
      - catalogdb
    ports:
      - "8002:443"
    volumes:
      - ~/.aspnet/https:/https:ro
  
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=8004
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456-a
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "CacheSettings:ConnectionString=basketdb:6379" 
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672" 
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8004:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=8006
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456-a
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb  
    ports:
      - "8006:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORT=8007
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8007:80"
    volumes:
      - ~/.aspnet/https:/https:ro

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=8010
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456-a
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672" 
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "8010:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=8012
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456-a
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "8012:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=8014
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456-a
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "ApiSettings:CatalogUrl=https://catalog.api"
      - "ApiSettings:BasketUrl=https://basket.api"
      - "ApiSettings:OrderingUrl=https://ordering.api"
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "8014:443"
    volumes:
      - ~/.aspnet/https:/https:ro
